# Generated by Django 4.0.4 on 2023-06-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.IntegerField(choices=[(0, 'Class Teacher'), (1, 'Head of the Room'), (2, 'Student')], default=2),
        ),
    ]
